project_id = "qmbshvfezrgqoyohjaac"

[functions.generate-insights]
verify_jwt = true

[functions.analyze-meal]
verify_jwt = true

[functions.passkey-register]
verify_jwt = true

[functions.passkey-authenticate]
verify_jwt = false